export type PetSpecies = "dog" | "cat" | "rabbit" | "capybara" | "quokka";
export type EarShape = "point" | "floppy" | "round";
export type Pattern =
  "solid" | "spots" | "stripes" | "mask" | "tuxedo" | "patches" | "points" | "blaze";
export type Accessory =
  "collar" | "tag" | "scarf" | "bow" | "glasses" | "bandana" | "crown" | "flower";

export type PetDesign = {
  id: string;
  species: PetSpecies;
  breed: string;
  name: string;
  body: string;
  secondary: string;
  accent: string;
  ear: EarShape;
  pattern: Pattern;
  accessories: Accessory[];
  unlock?: { mission: string; hint: string };
};

export const PETS: readonly PetDesign[] = [
  {
    id: "dog-shiba",
    species: "dog",
    breed: "시바견",
    name: "단풍",
    body: "#c8793b",
    secondary: "#fff0cf",
    accent: "#df5252",
    ear: "point",
    pattern: "points",
    accessories: ["bandana", "tag"],
  },
  {
    id: "dog-dalmatian",
    species: "dog",
    breed: "달마시안",
    name: "도트",
    body: "#f5f0df",
    secondary: "#292c38",
    accent: "#e8505b",
    ear: "floppy",
    pattern: "spots",
    accessories: ["collar", "tag"],
  },
  {
    id: "dog-beagle",
    species: "dog",
    breed: "비글",
    name: "호두",
    body: "#b96d38",
    secondary: "#f6e7c5",
    accent: "#4b77be",
    ear: "floppy",
    pattern: "patches",
    accessories: ["collar", "tag"],
  },
  {
    id: "dog-poodle",
    species: "dog",
    breed: "푸들",
    name: "모카",
    body: "#8b553f",
    secondary: "#d8a878",
    accent: "#ee8caf",
    ear: "round",
    pattern: "solid",
    accessories: ["bow", "collar"],
  },
  {
    id: "dog-corgi",
    species: "dog",
    breed: "웰시코기",
    name: "버터",
    body: "#d99145",
    secondary: "#fff2ce",
    accent: "#55a68c",
    ear: "point",
    pattern: "blaze",
    accessories: ["scarf", "tag"],
  },
  {
    id: "dog-schnauzer",
    species: "dog",
    breed: "슈나우저",
    name: "후추",
    body: "#777b83",
    secondary: "#d5d3ca",
    accent: "#df9d45",
    ear: "round",
    pattern: "blaze",
    accessories: ["glasses", "bow"],
  },
  {
    id: "dog-retriever",
    species: "dog",
    breed: "골든리트리버",
    name: "햇살",
    body: "#dba95c",
    secondary: "#ffe2a3",
    accent: "#579b68",
    ear: "floppy",
    pattern: "solid",
    accessories: ["collar", "flower"],
  },
  {
    id: "dog-husky",
    species: "dog",
    breed: "허스키",
    name: "설이",
    body: "#707786",
    secondary: "#ecf0ef",
    accent: "#579bd3",
    ear: "point",
    pattern: "mask",
    accessories: ["scarf", "tag"],
  },
  {
    id: "dog-collie",
    species: "dog",
    breed: "보더콜리",
    name: "구름",
    body: "#292e39",
    secondary: "#f2eee2",
    accent: "#d95858",
    ear: "point",
    pattern: "blaze",
    accessories: ["bandana", "flower"],
  },
  {
    id: "dog-maltese",
    species: "dog",
    breed: "말티즈",
    name: "솜이",
    body: "#f3f0e9",
    secondary: "#d9dce1",
    accent: "#e986ad",
    ear: "round",
    pattern: "solid",
    accessories: ["bow", "collar", "tag"],
  },
  {
    id: "cat-orange-tabby",
    species: "cat",
    breed: "치즈태비",
    name: "치즈",
    body: "#e39842",
    secondary: "#ffe2a4",
    accent: "#4c9c73",
    ear: "point",
    pattern: "stripes",
    accessories: ["collar", "tag"],
  },
  {
    id: "cat-tuxedo",
    species: "cat",
    breed: "턱시도",
    name: "연미",
    body: "#272c36",
    secondary: "#f2eee2",
    accent: "#d75b68",
    ear: "point",
    pattern: "tuxedo",
    accessories: ["bow", "tag"],
  },
  {
    id: "cat-siamese",
    species: "cat",
    breed: "샴",
    name: "라떼",
    body: "#ead6ad",
    secondary: "#65564f",
    accent: "#5d9bcf",
    ear: "point",
    pattern: "points",
    accessories: ["collar", "tag"],
  },
  {
    id: "cat-russian-blue",
    species: "cat",
    breed: "러시안블루",
    name: "안개",
    body: "#78838e",
    secondary: "#aeb7bc",
    accent: "#dfaa4b",
    ear: "point",
    pattern: "solid",
    accessories: ["scarf", "flower"],
  },
  {
    id: "cat-calico",
    species: "cat",
    breed: "삼색이",
    name: "송이",
    body: "#f2ead7",
    secondary: "#d47d43",
    accent: "#e3819c",
    ear: "point",
    pattern: "patches",
    accessories: ["collar", "flower"],
  },
  {
    id: "cat-black",
    species: "cat",
    breed: "블랙캣",
    name: "밤이",
    body: "#252938",
    secondary: "#60677b",
    accent: "#b688df",
    ear: "point",
    pattern: "solid",
    accessories: ["collar", "tag", "crown"],
  },
  {
    id: "cat-white",
    species: "cat",
    breed: "터키시앙고라",
    name: "소금",
    body: "#f6f2e9",
    secondary: "#dbe5e8",
    accent: "#e7b54d",
    ear: "point",
    pattern: "solid",
    accessories: ["crown", "collar"],
  },
  {
    id: "cat-brown-tabby",
    species: "cat",
    breed: "고등어태비",
    name: "보리",
    body: "#9b7c5d",
    secondary: "#d6bd90",
    accent: "#507f95",
    ear: "point",
    pattern: "stripes",
    accessories: ["glasses", "bandana"],
  },
  {
    id: "cat-ragdoll",
    species: "cat",
    breed: "랙돌",
    name: "마시멜로",
    body: "#eee3cf",
    secondary: "#8b8491",
    accent: "#7aa6d3",
    ear: "point",
    pattern: "mask",
    accessories: ["bow", "tag"],
  },
  {
    id: "cat-bicolor",
    species: "cat",
    breed: "브리티시숏헤어",
    name: "자갈",
    body: "#8e98a5",
    secondary: "#f1eee6",
    accent: "#dc775f",
    ear: "round",
    pattern: "tuxedo",
    accessories: ["bandana", "collar", "tag"],
  },
  {
    id: "rabbit-yuzu",
    species: "rabbit",
    breed: "노란 토끼",
    name: "유자",
    body: "#f3d99b",
    secondary: "#fff1c7",
    accent: "#e86a47",
    ear: "point",
    pattern: "solid",
    accessories: [],
    unlock: {
      mission: "하루에 업무 10개 완료",
      hint: "아주 바쁜 하루를 보내면 만날지도?",
    },
  },
  {
    id: "capybara-gamja",
    species: "capybara",
    breed: "카피바라",
    name: "감자",
    body: "#a8784f",
    secondary: "#d9b184",
    accent: "#e7a43b",
    ear: "round",
    pattern: "solid",
    accessories: [],
    unlock: {
      mission: "프로젝트 루트 1개 등록",
      hint: "새로운 작업 공간을 열면 찾아올지도?",
    },
  },
  {
    id: "quokka-bangul",
    species: "quokka",
    breed: "쿼카",
    name: "방울",
    body: "#8f6b50",
    secondary: "#d9b895",
    accent: "#62a36b",
    ear: "round",
    pattern: "solid",
    accessories: ["bandana"],
    unlock: {
      mission: "2명 이상의 동료가 참여한 워크플로 완료",
      hint: "여럿이 힘을 합치면 웃음소리가 들릴지도?",
    },
  },
];

export function getPet(id?: string, fallbackIndex = 0): PetDesign {
  const defaultPets = PETS.filter((pet) => !pet.unlock);
  return (
    PETS.find((pet) => pet.id === id) ?? defaultPets[Math.abs(fallbackIndex) % defaultPets.length]!
  );
}

export const UNLOCKABLE_PETS = PETS.filter((pet) => pet.unlock !== undefined);

export function isPetId(id: string): boolean {
  return PETS.some((pet) => pet.id === id);
}
